general:
  vulnerabilities:
    - CVE-2021-3999
    - CVE-2022-2097 # only affects 32-bit x86 platforms. We don't offer this architecture in docker however.
    - CVE-2023-0464 # only affects us, if user explicitly passes "-policy" to curl. We simply accept that case.
    - CVE-2023-0465 # same as above (CVE-2023-0464)
    - CVE-2023-0466 # only applies when X509_V_FLAG_POLICY_CHECK is set as a flag. curl cannot be invoked in protocurl this way.
  bestPracticeViolations:
    - DKL-LI-0001
    - CIS-DI-0005
    - CIS-DI-0006
